language: ruby
rvm:
  - 2.2
env:
  - DB=pgsql
services:
  - postgresql
before_script:
  - RAILS_ENV=test bundle exec rake db:create
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
